# Generated by Django 5.2.4 on 2025-08-02 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Password History', 'verbose_name_plural': 'Password History'},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System Setting', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_activity'], 'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='admin_dashb_user_id_7055ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='admin_dashb_action_ed536c_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='admin_dashb_content_f83142_idx',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='description',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.AlterUniqueTogether(
            name='systemsettings',
            unique_together={('setting_type', 'setting_key')},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('ADMIN_DASHBOARD_ACCESS', 'Admin Dashboard Access'), ('CUSTOM_REPORTS_ACCESS', 'Custom Reports Access'), ('AUDIT_LOGS_ACCESS', 'Audit Logs Access'), ('SESSION_MANAGEMENT_ACCESS', 'Session Management Access'), ('SECURITY_SETTINGS_ACCESS', 'Security Settings Access'), ('BULK_OPERATIONS_ACCESS', 'Bulk Operations Access'), ('TIMEOUT_SETTINGS_UPDATE', 'Timeout Settings Update'), ('PASSWORD_POLICY_UPDATE', 'Password Policy Update'), ('FORCE_LOGOUT', 'Force Logout'), ('BULK_USER_IMPORT', 'Bulk User Import'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('BOOK_CREATE', 'Book Created'), ('BOOK_UPDATE', 'Book Updated'), ('BOOK_DELETE', 'Book Deleted'), ('BORROWING_CREATE', 'Borrowing Created'), ('BORROWING_UPDATE', 'Borrowing Updated'), ('FINE_CREATE', 'Fine Created'), ('FINE_UPDATE', 'Fine Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='setting_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='setting_type',
            field=models.CharField(choices=[('SESSION_TIMEOUT', 'Session Timeout'), ('PASSWORD_POLICY', 'Password Policy'), ('FINE_SETTINGS', 'Fine Settings'), ('BORROWING_LIMITS', 'Borrowing Limits'), ('RESERVATION_TIMEOUT', 'Reservation Timeout')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='setting_value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='is_active',
        ),
    ]
