# Generated by Django 5.2.4 on 2025-08-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_add_simple_system_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='usersession',
            name='timeout_minutes',
            field=models.IntegerField(default=15, help_text='Session timeout in minutes'),
        ),
    ]
