# Generated by Django 5.2.4 on 2025-08-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_update_user_session_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Changed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('FORCE_LOGOUT', 'Force Logout'), ('SESSION_TIMEOUT', 'Session Timeout'), ('MULTIPLE_LOGIN_FAILURES', 'Multiple Login Failures'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('USER_ROLE_CHANGE', 'User Role Changed'), ('BOOK_CREATE', 'Book Created'), ('BOOK_UPDATE', 'Book Updated'), ('BOOK_DELETE', 'Book Deleted'), ('BOOK_VIEW', 'Book Viewed'), ('BOOK_BORROW', 'Book Borrowed'), ('BOOK_RETURN', 'Book Returned'), ('BORROWING_APPROVE', 'Borrowing Approved'), ('BORROWING_REJECT', 'Borrowing Rejected'), ('EXTENSION_REQUEST', 'Extension Requested'), ('EXTENSION_APPROVE', 'Extension Approved'), ('RESERVATION_CREATE', 'Reservation Created'), ('RESERVATION_APPROVE', 'Reservation Approved'), ('RESERVATION_REJECT', 'Reservation Rejected'), ('RESERVATION_EXPIRE', 'Reservation Expired'), ('FINE_CREATE', 'Fine Created'), ('FINE_PAID', 'Fine Paid'), ('FINE_WAIVE', 'Fine Waived'), ('FINE_UPDATE', 'Fine Updated'), ('ADMIN_DASHBOARD_ACCESS', 'Admin Dashboard Access'), ('AUDIT_LOGS_ACCESS', 'Audit Logs Access'), ('SESSION_MANAGEMENT_ACCESS', 'Session Management Access'), ('SETTING_UPDATE', 'System Setting Updated'), ('UPDATE_TIMEOUT', 'Session Timeout Updated'), ('BULK_OPERATION', 'Bulk Operation Performed'), ('LOGIN', 'User Login'), ('BORROWING_CREATE', 'Borrowing Created'), ('BORROWING_UPDATE', 'Borrowing Updated')], max_length=50),
        ),
    ]
