"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t58g$8d=h_7w+k10_%(-io9c(u6&y0!w&ml$4vl(gltyrtgv_4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# CSRF Trusted Origins for HTTPS demo
CSRF_TRUSTED_ORIGINS = [
    'https://127.0.0.1:8443',
    'https://localhost:8443',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library',
    'tailwind',
    'theme',
    'django_browser_reload',
    'branches',
    'users',
    'borrow',
    'reservations',
    'fines',
    'privacy',
    'widget_tweaks',
    'django.contrib.humanize',
    'admin_dashboard',
]

TAILWIND_APP_NAME = 'theme'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'hsts_middleware.HSTSMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Static files configuration
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'theme', 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/users/login/'  # Add this line

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'admin_dashboard.auth_backends.LibraryManagementAuditAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

NPM_BIN_PATH = "/usr/local/bin/npm"

# Account Lock Settings
ACCOUNT_LOCK_SETTINGS = {
    'MAX_FAILED_ATTEMPTS': 5,
    'LOCK_DURATION_MINUTES': 5,
    'WARNING_THRESHOLD': 3,
    'AFFECTED_USER_ROLES': ['member', 'librarian', 'manager']
}

# Session Timeout Settings (in minutes)
SESSION_TIMEOUT_BY_ROLE = {
    'member': 15,        # 15 minutes for regular members
    'librarian': 15,     # 15 minutes for librarians
    'manager': 30,       # 30 minutes for managers (can be adjusted)
    'admin': 30,         # 30 minutes for admins (can be adjusted)
}

# Password Policy Settings
PASSWORD_POLICY = {
    'ADMIN_MANAGER_EXPIRY_DAYS': 0.000694444,  # 6 months
    'FORCE_CHANGE_ON_FIRST_LOGIN': True,
}
# HSTS and Security Settings for Demo
# This is a key setting for HSTS. It specifies the duration (in seconds)
# that the browser should remember the HSTS policy.
# For a demo, a small value is fine (e.g., 3600 seconds = 1 hour).
# For a production app, this should be a much larger number (e.g., 31536000 for one year).
SECURE_HSTS_SECONDS = 3600

# This setting tells the browser to also apply the HSTS policy to all subdomains.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# This tells the browser to automatically redirect all HTTP requests to HTTPS.
# Since the secure server will only serve HTTPS, this is a good
# way to ensure the demo is secure from the start.
# SECURE_SSL_REDIRECT = True  # Temporarily disabled to avoid redirect loops

# These are good to include for a comprehensive security demo.
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Additional security headers for HTTPS demo
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'