# Generated by Django 5.2.4 on 2025-07-05 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('days_overdue', models.PositiveIntegerField()),
                ('paid', models.BooleanField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrow.borrowing')),
            ],
        ),
    ]
