# Generated by Django 5.2.4 on 2025-07-22 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fine',
            name='fine_type',
            field=models.CharField(choices=[('overdue', 'Overdue Fine'), ('damaged', 'Damaged/Lost Book')], default='overdue', max_length=20),
        ),
        migrations.AlterField(
            model_name='fine',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
