# Generated by Django 5.2.4 on 2025-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_fine_created_at_fine_fine_type_alter_fine_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
