# Generated by Django 5.2.4 on 2025-08-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_password_policy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_date',
            field=models.DateTimeField(blank=True, help_text='Date when consent was given', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Consent to receive marketing communications'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_consent',
            field=models.BooleanField(default=False, help_text='Consent to process personal data'),
        ),
    ]
