# Generated by Django 5.2.4 on 2025-07-22 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_borrowing_approved_date_borrowing_pickup_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_borrowings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('borrowed', 'Borrowed'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
